apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3xum
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-3xum
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-3xum
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3xum
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-3xum
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-edfa-tenant/dotnet-component/devfile-sample-dotnet60-basic-3xum@sha256:3afde7ba781e8ecd2e831fae2f0ca23c819d02285922d219950f2147700a1f8c
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
