apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-3xum
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-edfa-tenant/dotnet-component/devfile-sample-dotnet60-basic-3xum@sha256:3afde7ba781e8ecd2e831fae2f0ca23c819d02285922d219950f2147700a1f8c
        name: main
        resources: {}
status: {}
